name: Send GH PR metrics to Monday Board

on:
  push:
    branches:
      - main

jobs:
  call-gh-pr-metrics-to-monday:
    uses: saularraffi/gh-metrics-to-monday/.github/workflows/github-churn-to-monday.yml@main
    with:
      repo-owner: ${{ github.repository_owner }}
      repo-name: ${{ github.event.repository.name }}
    secrets: inherit
