on:
  push:
    branches:
      - main

jobs:
  call-gh-pr-metrics-to-monday:
    runs-on: ubuntu-latest
    steps:
      - name: Call GH PR Metrics to Monday
        uses: saularraffi/test/.github/workflows/github-churn-to-monday.yml@main
        with:
          repo-owner: saularraffi
          repo-name: test
        secrets: inherit
