name: Send GH PR metrics to Monday Board

on:
  push:
    branches:
      - main

jobs:
  call-gh-pr-metrics-to-monday:
    uses: saularraffi/github-metrics/.github/workflows/github-churn-metrics.yml@main
    with:
      repo-owner: ${{ github.repository_owner }}
      repo-name: ${{ github.event.repository.name }}
    secrets: inherit
